use_frameworks!

platform :ios, '9.0'

target 'YWXSignSDK_Example' do
  pod 'YWXSignSDK', :path => '../'

  target 'YWXSignSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
