use_frameworks!

platform :ios, '10.0'

abstract_target 'Example' do
  pod 'YWXSignSDK', :path => '../'

  target 'YWXSignSDK_Example' do
    target 'YWXSignSDK_Tests' do
      inherit! :search_paths

      pod 'FBSnapshotTestCase'
    end
  end
  
  target 'YWXBjcaSignSDK_Example' do
    pod 'YWXSignSDK/YWXBjcaSignSDK', :path => '../'
  end
end
